services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Kolkata
    group_add:
      - 983
      - 987
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - /media/anime:/anime
      - /media/movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: on-failure
    ports:
      - 8096:8096
